# This file contains localization messages for different languages
# and language parameters chosen by users.
# It serves as a central repository for storing language-specific texts
# and provides a convenient way to manage multilingual support within the bot.

START_MESSAGES = {
    "🇬🇧 English": "<b>Welcome to the <a href=\"https://t.me/QRCreateBot\">QR Creator</a>.</b> 🚀\n\nThis bot is your <b>personal QR code generator and decoder</b>. Simply send me text or a link, and I'll instantly craft a QR code for you in all its glory. And if you have an image with a QR code, don't worry — I'll decrypt its contents!\n\n<b>🤔 How the bot works?</b>\n\n📤 Send me text or a link.\n🎨 Receive a ready-to-use QR code in response.\n📥 Alternatively, upload an image with a QR code.\n🕵️‍♂️ I'll read it and send you information from the QR code.\n\n<b>Simple, convenient, and free.</b>",
    "🇷🇺 Русский": "<b>Добро пожаловать в <a href=\"https://t.me/QRCreateBot\">QR Creator</a>.</b> 🚀\n\nЭтот бот — твой <b>персональный генератор и декодер QR-кодов</b>. Просто отправь мне текст или ссылку, и я мгновенно сотворю для тебя QR-код во всей его красе. А если у тебя есть изображение с QR-кодом, не парься — я расшифрую его содержимое!\n\n<b>🤔 Как работает бот?</b>\n\n📤 Отправь мне текст или ссылку.\n🎨 Получи готовый QR-код в ответ.\n📥 И наоборот: загрузи изображение с QR-кодом.\n🕵️‍♂️ Я прочту его и отправлю тебе информацию с QR-кода.\n\n<b>Просто, удобно и бесплатно.</b>",
    "🇵🇹 Português": "<b>Bem-vindo ao mundo do <a href=\"https://t.me/QRCreateBot\">QR Creator</a>.</b> 🚀\n\nEste bot é o seu gerador <b>pessoal de códigos QR e decodificador</b>. Basta me enviar texto ou um link, e instantaneamente criarei um código QR para você em todo o seu esplendor. E se você tiver uma imagem com um código QR, não se preocupe — decifrarei seu conteúdo!\n\n<b>🤔 Como o bot funciona?</b>\n\n📤 Envie-me texto ou um link.\n🎨 Receba um código QR pronto para uso como resposta.\n📥 Ou, alternativamente, envie uma imagem com um código QR.\n🕵️‍♂️ Eu o lerei e enviarei a você informações do código QR.\n\n<b>Simples, conveniente e gratuito.</b>",
    "🇮🇩 Indonesia": "<b>Selamat datang di dunia <a href=\"https://t.me/QRCreateBot\">QR Creator</a>.</b> 🚀\n\nBot ini <b>adalah generator dan dekoder kode QR pribadi Anda</b>. Cukup kirimkan saya teks atau tautan, dan saya akan segera membuat kode QR untuk Anda dengan segala keindahannya. Dan jika Anda memiliki gambar dengan kode QR, jangan khawatir — saya akan mendekripsi isinya!\n\n🤔<b> Bagaimana cara kerja bot?</b>\n\n📤 Kirimkan saya teks atau tautan.\n🎨 Dapatkan kode QR siap pakai sebagai respons.\n📥 Atau, sebagai alternatif, unggah gambar dengan kode QR.\n🕵️‍♂️ Saya akan membacanya dan mengirimkan informasi dari kode QR.\n\n<b>Sederhana, nyaman, dan gratis.</b>",
    "🇪🇸 Español": "<b>Bienvenido al mundo de <a href=\"https://t.me/QRCreateBot\">QR Creator</a>.</b> 🚀\n\nEste bot es tu <b>generador personal de códigos QR y decodificador</b>. Solo envíame texto o un enlace, ¡y al instante crearé un código QR para ti en todo su esplendor! Y si tienes una imagen con un código QR, no te preocupes, ¡descifraré su contenido!\n\n<b>🤔 ¿Cómo funciona el bot?</b>\n\n📤 Envíame texto o un enlace.\n🎨 Recibe un código QR listo para usar como respuesta.\n📥 O, alternativamente, envía una imagen con un código QR.\n🕵️‍♂️ Lo leeré y te enviaré información del código QR.\n\n<b>Simple, conveniente y gratuito.</b>",
    "🇺🇿 O'zbek tili": "<b>Xush kelibsiz <a href=\"https://t.me/QRCreateBot\">QR Creator'ga</a>.</b> 🚀\n\nBu bot, <b>shaxsiy QR-kod yaratuvchisi va doirabchisi sifatida xizmat qiladi</b>. Iltimos, menga matn yoki havola yuboring, va men avval-oxtat QR-kod yarata olaman. Agar sizda QR-kod bilan surat mavjud bo'lsa, xavotiror bo'lmang — men uni ma'lumotini ochib beraman!\n\n<b>🤔 Bot qanday ishlaydi?</b>\n\n📤 Menga matn yoki havola yuboring.\n🎨 Javob sifatida ishlatish uchun tayyor QR-kod oling.\n📥 Yoki alternativ ravishda, QR-kod bilan tasvir yuboring.\n🕵️‍♂️ Men uni o'qib, QR-kod ma'lumotlarini yuboraman.\n\n<b>Oddiy, qulay va bepul!</b>"
}


HELP_MESSAGES = {
    "🇬🇧 English": "<b>🛠 Create QR Code with @QRCreateBot.</b>\n\nWelcome to <b>QRCreate Bot</b>I'm here to help you generate QR codes quickly and easily.\n\n🚀 How to use:\n Just send me the link or text you want to add to a QR code, and I'll craft it for you in seconds.\n\n📖 Learn more:\n   Explore our <a href=\"https://telegra.ph/FAQ--Bot-and-Creating-a-QR-Code-12-03\">FAQ — Bot and Creating a QR Code</a> for detailed instructions.\n\n    🤖 Have other questions?\n    Feel free to ask! I'm here to assist you.\n\n 🌟 Enjoy creating QR codes with QRCreate Bot!",
    "🇷🇺 Русский": "<b>🛠 Создайте QR-код с @QRCreateBot.</b>\n\nДобро пожаловать в <b>QRCreate Bot</b>, я здесь, чтобы помочь вам быстро и легко создавать QR-коды.\n\n🚀 Как использовать:\n Просто отправьте мне ссылку или текст, который вы хотите добавить в QR-код, и я мгновенно создам его для вас.\n\n📖 Узнайте больше:\n   Изучите наше <a href=\"https://telegra.ph/FAQ--Bot-and-Creating-a-QR-Code-12-03\">руководство по созданию QR кодов</a> для подробных инструкций.\n\n    🤖 Есть другие вопросы?\n    Не стесняйтесь спрашивать! Я здесь, чтобы помочь.\n\n 🌟 Наслаждайтесь созданием QR-кодов с QRCreate Bot!",
    "🇵🇹 Português": "<b>🛠 Crie um Código QR com @QRCreateBot.</b>\n\nBem-vindo ao <b>QRCreate Bot</b>, estou aqui para ajudar você a gerar códigos QR de maneira rápida e fácil.\n\n🚀 Como usar:\n Basta me enviar o link ou texto que você deseja adicionar a um código QR, e eu o criarei para você em segundos.\n\n📖 Saiba mais:\n   Explore nosso <a href=\"https://telegra.ph/FAQ--Bot-and-Creating-a-QR-Code-12-03\">FAQ - Bot e Criação de um Código QR</a>para instruções detalhadas.\n\n    🤖 Tem outras perguntas?\n    Sinta-se à vontade para perguntar! Estou aqui para ajudar.\n\n 🌟 Aproveite a criação de códigos QR com o QRCreate Bot!",
    "🇮🇩 Indonesia": "<b>🛠 Buat Kode QR dengan @QRCreateBot.</b>\n\nSelamat datang di <b>QRCreate Bot</b>, saya di sini untuk membantu Anda membuat kode QR dengan cepat dan mudah.\n\n🚀 Cara penggunaan:\n Cukup kirimkan saya tautan atau teks yang ingin Anda tambahkan ke kode QR, dan saya akan membuatnya untuk Anda dalam hitungan detik.\n\n📖 Pelajari lebih lanjut:\n   Telusuri <a href=\"https://telegra.ph/FAQ--Bot-and-Creating-a-QR-Code-12-03\">FAQ - Bot dan Membuat Kode QR</a> kami untuk petunjuk rinci.\n\n    🤖 Punya pertanyaan lain?\n    Jangan ragu untuk bertanya! Saya di sini untuk membantu Anda.\n\n 🌟 Nikmati membuat kode QR dengan QRCreate Bot!",
    "🇪🇸 Español": "<b>🛠 Crea un código QR con @QRCreateBot.</b>\n\nBienvenido a <b>QRCreate Bot</b>, estoy aquí para ayudarte a generar códigos QR de manera rápida y sencilla.\n\n🚀 Cómo usar:\n Simplemente envíame el enlace o texto que deseas agregar a un código QR, y lo crearé para ti en segundos.\n\n📖 Más información:\n   Explora nuestras <a href=\"https://telegra.ph/FAQ--Bot-and-Creating-a-QR-Code-12-03\">Preguntas frecuentes - Bot y Creación de un Código QR</a> para obtener instrucciones detalladas.\n\n    🤖 ¿Tienes otras preguntas?\n    ¡No dudes en preguntar! Estoy aquí para ayudarte.\n\n 🌟 Disfruta creando códigos QR con QRCreate Bot!",
    "🇺🇿 O'zbek tili": "<b>🛠 QR-Kod yaratishda @QRCreateBot bilan.</b>\n\n<b>QRCreate Bot</b>ga xush kelibsiz, men sizga tezkor va oson QR kodlarini yaratishda yordam bera olish uchun bu yerda bo'lamiz.\n\n🚀 Qanday foydalanish:\n Faqat menga QR kodga qo'shmoqchi bo'lgan havolani yoki matnni yuboring, va men bir necha soniyada unga ega bo'lgan QR kodni yarataman.\n\n📖 Ko'proq ma'lumot:\n   Detallangan yo'riqnoma uchun <a href=\"https://telegra.ph/FAQ--Bot-and-Creating-a-QR-Code-12-03\">[FAQ] — Bot va QR-Kod yaratish</a>imizni o'qib chiqing.\n\n    🤖 Boshqa savollaringiz bormi?\n    O'z fikrlaringizni so'rang! Men bu erda yordam bera olish uchun tayyorman.\n\n 🌟 QRCreate Bot bilan QR kodlarini yaratishning tadini do'zaxlang!"
}

PRIVACY_MESSAGES = {
    "🇬🇧 English": "Please don't create fraudulent, pornographic, or illegal links. If you use this bot for malicious QR codes and forbidden links — please stop the bot. Thank you!<b>Best wishes, QRCreate Bot Developer.</b>",
    "🇷🇺 Русский": "Пожалуйста, не создавайте мошеннические, порнографические, или незаконные ссылки. Если Вы используете этот бот для создания вредоносных QR-кодов и запрещенных ссылок — пожалуйста, остановите бота. Спасибо!<b>С наилучшими пожеланиями, разработчик QRCreate Bot.</b>",
    "🇵🇹 Português": "Por favor, não crie links fraudulentos, pornográficos, ou ilegais. Se você usar este bot para QR codes maliciosos e links proibidos — por favor, pare o bot. Obrigado!<b>Melhores votos, Desenvolvedor do QRCreate Bot.</b>",
    "🇮🇩 Indonesia": "Harap tidak membuat tautan palsu, pornografi, atau ilegal. Jika Anda menggunakan bot ini untuk membuat QR code jahat dan tautan terlarang — tolong hentikan bot. Terima kasih!<b>Salam terbaik, Pengembang QRCreate Bot.</b>",
    "🇪🇸 Español": "Por favor, no crees enlaces fraudulentos, pornográficos, o ilegales. Si utilizas este bot para crear códigos QR maliciosos y enlaces prohibidos — por favor, detén el bot. ¡Gracias!<b>Mejores deseos, Desarrollador de QRCreate Bot.</b>",
    "🇺🇿 O'zbek tili": "Iltimos, qandaydir yolg'on, pornografiya yoki qonunsiz havolalar yaratmang. Agar siz bu botni zararli QR-kodlar va taqiqlangan havolalar yaratish uchun ishlatasizsa, iltimos, botni to'xtating. Rahmat!<b>Eng yaxshi takliflar, QRCreate Bot dasturchisi.</b>"
}

GREETING_MESSAGES = {
    "🇬🇧 English": {"morning": "Good morning", "afternoon": "Good afternoon", "evening": "Good evening", "night": "Good night"},
    "🇷🇺 Русский": {"morning": "Доброе утро", "afternoon": "Добрый день", "evening": "Добрый вечер", "night": "Доброй ночи"},
    "🇵🇹 Português": {"morning": "Bom dia", "afternoon": "Boa tarde", "evening": "Boa noite", "night": "Boa noite"},
    "🇮🇩 Indonesia": {"morning": "Selamat pagi", "afternoon": "Selamat siang", "evening": "Selamat malam", "night": "Selamat malam"},
    "🇪🇸 Español": {"morning": "Buenos días", "afternoon": "Buenas tardes", "evening": "Buenas noches", "night": "Buenas noches"},
    "🇺🇿 O'zbek tili": {"morning": "Hayirli tong", "afternoon": "Hayirli kun", "evening": "Hayirli kech", "night": "Hayirli kech"},
    "set_language:uz-latin": {"morning": "Hayirli tong", "afternoon": "Hayirli kun", "evening": "Hayirli kech", "night": "Hayirli kech"}
}

INSTRUCTIONS_MESSAGES = {
    "🇬🇧 English": "If you want to create a QR code from your text or link, send me the text or link, and I'll provide you with the ready result. I can also decode a QR code and send you its content.\n\n<b>What kind of QR code would you like to create?</b> ☺️",
    "🇷🇺 Русский": "Если ты хочешь создать QR-код из твоего текста или ссылки, отправь мне текст или ссылку и я отправлю тебе готовый результат. Я также могу декодировать QR-код и отправить тебе содержимое QR-кода.\n\n<b>Какой QR-код будем создавать?</b> ☺️",
    "🇵🇹 Português": "Se você deseja criar um código QR a partir do seu texto ou link, me envie o texto ou link, e eu lhe fornecerei o resultado pronto. Também posso decodificar um código QR e enviar a você o seu conteúdo.\n\n<b>Que tipo de QR code você gostaria de criar?</b> ☺️",
    "🇮🇩 Indonesia": "Jika Anda ingin membuat kode QR dari teks atau tautan Anda, kirimkan saya teks atau tautan, dan saya akan memberikan hasil yang siap. Saya juga dapat mendekode kode QR dan mengirimkan Anda isinya.\n\n<b>QR code seperti apa yang ingin Anda buat?</b> ☺️",
    "🇪🇸 Español": "Si deseas crear un código QR a partir de tu texto o enlace, envíame el texto o enlace, y te proporcionaré el resultado listo. También puedo decodificar un código QR y enviarte su contenido.\n\n<b>¿Qué tipo de código QR te gustaría crear?</b> ☺️",
    "🇺🇿 O'zbek tili": "Agar siz o'zingizning matningiz yoki havolangizdan QR-kod yaratmoqchi bo'lsangiz, matn yoki havolani menga yuboring, va men sizga tayyor natijani taqdim qilaman. Shuningdek, men QR-kodni dekod qilishim va uning ma'lumotlarini sizga yuborishim mumkin.\n\n<b>Siz qanday turi QR-kod yaratmoqchisiz?</b> ☺️",
}

BOTS_MESSAGES = {
    "🇬🇧 English": "<b>Our goal is to develop free and useful tools in the form of Telegram chat bots. We also have other interesting chat bots for your consideration, and all of them are free.</b> Here is a list of some of our chat bots:\n<b>@SharingFilesRobot</b> – a bastion of secure and clandestine archival for your digital files;\n<b>@EnFactsBot</b> – a repository of perpetual enlightenment, ceaselessly furnishing captivating vignettes from the far reaches of our planet;\n<b>@TgProxoBot</b> – a cornucopia of gratis proxy servers spanning the gamut of <b>SOCK4</b>, <b>SOCK5</b>, and <b>HTTP</b> protocols.\n<b>@idinfosteambot</b>– by submitting a <b>Steam ID</b>, you may glean a trove of intelligence concerning your Steam account.\n\n<b>You can subscribe to our Telegram channel to stay updated with the latest news!</b>",
    "🇷🇺 Русский": "<b>Наша цель – разработка  бесплатных и полезных инструментов в виде чат-ботов для Telegram. У нас также имеются и другие интересные чат-боты к вашему вниманию, и все они бесплатны.</b> Вот список некоторых наших чат-ботов:\n\n<b>@SharingFilesRobot</b> – самый безопасный и тайный архив Ваших цифровых файлов;\n<b>@EnFactsBot</b> – репозиторий интересных фактов, предоставляющий увлекательные факты из далеких уголков нашей планеты;\n<b>@TgProxoBot</b> – прокси-сервера, охватывающие всю гамму протоколов <b>SOCK4</b>, <b>SOCK5</b> и <b>HTTP</b>.\n<b>@idinfosteambot</b>– отправив <b>Steam ID</b>, Вы можете получить множество сведений о своей учетной записи Steam.\n\n<b>Вы можете подписаться на наш Telegram-канал, чтобы быть в курсе последних новостей!</b>",
    "🇵🇹 Português": "<b>Nosso objetivo é desenvolver ferramentas gratuitas e úteis na forma de chat bots para o Telegram. Também temos outros chat bots interessantes para a sua consideração, e todos eles são gratuitos.</b> Aqui está uma lista de alguns dos nossos chat bots:\n<b>@SharingFilesRobot</b> – um bastião de arquivamento seguro e clandestino para seus arquivos digitais;\n<b>@EnFactsBot</b> – um repositório de iluminação perpétua, fornecendo incessantemente vinhetas cativantes dos confins de nosso planeta;\n<b>@TgProxoBot</b> – uma cornucópia de servidores proxy gratuitos que abrangem os protocolos <b>SOCK4</b>, <b>SOCK5</b> e <b>HTTP</b>.\n<b>@idinfosteambot</b>– ao enviar um <b>Steam ID</b>, você pode obter um tesouro de informações sobre sua conta Steam.\n\n<b>Você pode se inscrever em nosso canal no Telegram para ficar atualizado com as últimas notícias!</b>",
    "🇮🇩 Indonesia": "<b>Tujuan kami adalah mengembangkan alat-alat gratis dan bermanfaat dalam bentuk bot obrolan Telegram. Kami juga memiliki bot obrolan menarik lainnya yang dapat Anda pertimbangkan, dan semuanya gratis.</b> Berikut adalah daftar beberapa bot obrolan kami:\n<b>@SharingFilesRobot</b> – benteng penyimpanan arsip yang aman dan rahasia untuk file digital Anda;\n<b>@EnFactsBot</b> – repositori pencerahan abadi, tanpa henti menyediakan adegan menarik dari ujung dunia kita;\n<b>@TgProxoBot</b> – cornucopia server proxy gratis yang mencakup berbagai protokol <b>SOCK4</b>, <b>SOCK5</b>, dan <b>HTTP</b>.\n<b>@idinfosteambot</b>– dengan mengirimkan <b>Steam ID</b>, Anda dapat mendapatkan sejumlah informasi tentang akun Steam Anda.\n\n<b>Anda dapat berlangganan saluran Telegram kami untuk tetap terkini dengan berita terbaru!</b>",
    "🇪🇸 Español": "<b>Nuestra meta es desarrollar herramientas gratuitas y útiles en forma de chat bots para Telegram. También contamos con otros chat bots interesantes para su consideración, y todos son gratuitos.</b> Aquí tienes una lista de algunos de nuestros chat bots:\n<b>@SharingFilesRobot</b> – un bastión de archivo seguro y clandestino para tus archivos digitales;\n<b>@EnFactsBot</b> – un repositorio de iluminación perpetua, que proporciona incesantemente viñetas cautivadoras desde los rincones más lejanos de nuestro planeta;\n<b>@TgProxoBot</b> – una cornucopia de servidores proxy gratis que abarcan los protocolos <b>SOCK4</b>, <b>SOCK5</b> y <b>HTTP</b>.\n<b>@idinfosteambot</b>– al enviar un <b>Steam ID</b>, puedes obtener un tesoro de información sobre tu cuenta de Steam.\n\n<b>Puedes suscribirte a nuestro canal de Telegram para estar al tanto de las últimas noticias!</b>",
    "🇺🇿 O'zbek tili": "<b>Bizning maqsadimiz Telegramda bepul va foydali vositalar shaklida chat-botlar ishlab chiqish. Bizning e'tirozli botlarimizni ko'rib chiqishingiz mumkin, ular hammasi bepul.</b> Quyidagi qisqacha ro'yxatda ba'zi botlarimiz:\n\n<b>@SharingFilesRobot</b> – sizning raqamingizni himoyalovchi va rahmatlanuvchi elektron arxiv;\n<b>@EnFactsBot</b> – doimiy ravishda sizga yoqimli voqealar taqdim etuvchi abadiy ma'lumotlar saqlash yeri;\n<b>@TgProxoBot</b> – <b>SOCK4</b>, <b>SOCK5</b> va <b>HTTP</b> protokollari doirasi bepul proxy serverlar xazinasidir.\n<b>@idinfosteambot</b>– <b>Steam ID</b>ni yuborish orqali, siz o'zingizning Steam hisobingiz haqida ma'lumotlarni olishingiz mumkin.\n\n<b>Siz Telegram kanalimizga obuna bo'lishingiz mumkin, yangiliklardan xabardor bo'lish uchun!</b>",
}

MAX_LENGTH_ERROR_MESSAGES = {
    "🇬🇧 English": "Your message contains more than 2953 characters. I cannot create a QR code that is too large due to technical limitations.",
    "🇷🇺 Русский": "В Вашем сообщении содержится более чем 2953 символа. Я не смогу создать слишком большой QR-код из-за технических ограничений.",
    "🇵🇹 Português": "Sua mensagem contém mais de 2953 caracteres. Não é possível criar um QR code muito grande devido a limitações técnicas.",
    "🇮🇩 Indonesia": "Pesan Anda berisi lebih dari 2953 karakter. Saya tidak dapat membuat QR code yang terlalu besar karena batasan teknis.",
    "🇪🇸 Español": "Tu mensaje contiene más de 2953 caracteres. No puedo crear un código QR tan grande debido a limitaciones técnicas.",
    "🇺🇿 O'zbek tili": "Sizning xabaringizda 2953 dan ortiq belgi mavjud. Texnik cheklovlar tufayli, juda katta QR-kod yaratolmayapti.",
}

CHANGE_LANG_ERROR = {
    "🇬🇧 English": "You are changing the language too often. Try again later.",
    "🇷🇺 Русский": "Вы слишком часто меняете языковой параметр. Попробуйте позже.",
    "🇵🇹 Português": "Você está mudando o idioma com muita frequência. Tente novamente mais tarde.",
    "🇮🇩 Indonesia": "Anda mengganti bahasa terlalu sering. Coba lagi nanti.",
    "🇪🇸 Español": "Estás cambiando el idioma con demasiada frecuencia. Inténtalo de nuevo más tarde.",
    "🇺🇿 O'zbek tili": "Siz tillarni juda ko'p o'zgartirayotganingizni aytdingiz. Keyinroq qayta urinib ko'ring.",
}

STICKER_RESPONSE = {
    "🇬🇧 English": "I haven't learned how to respond to stickers yet. But I'll definitely learn soon! :)",
    "🇷🇺 Русский": "Пока я не научился отвечать на стикеры. Но обязательно научусь скоро! :)",
    "🇵🇹 Português": "Eu ainda não aprendi a responder a adesivos. Mas com certeza vou aprender em breve! :)",
    "🇮🇩 Indonesia": "Saya belum tahu cara merespons stiker. Tapi saya pasti akan belajar segera! :)",
    "🇪🇸 Español": "Todavía no he aprendido a responder a los stickers. ¡Pero definitivamente aprenderé pronto! :)",
    "🇺🇿 O'zbek tili": "Men hali stikerlarga qanday javob bermoqni o'rganmamdim. Lekin albatta tez orada o'rganaman! :)",
}

VOICE_RESPONSE = {
    "🇬🇧 English": "I don't know how to respond to voice messages.",
    "🇷🇺 Русский": "Я не умею отвечать на голосовые сообщения.",
    "🇵🇹 Português": "Eu não sei como responder a mensagens de voz.",
    "🇮🇩 Indonesia": "Saya tidak tahu cara merespons pesan suara.",
    "🇪🇸 Español": "No sé cómo responder a mensajes de voz.",
    "🇺🇿 O'zbek tili": "Men ovozli xabarlarga qanday javob bermoqni bilmayman.",
}

VIDEO_RESPONSE = {
    "🇬🇧 English": "I don't know how to respond to videos.",
    "🇷🇺 Русский": "Я не умею отвечать на видео.",
    "🇵🇹 Português": "Eu não sei como responder a vídeos.",
    "🇮🇩 Indonesia": "Saya tidak tahu cara merespons video.",
    "🇪🇸 Español": "No sé cómo responder a videos.",
    "🇺🇿 O'zbek tili": "Men videoga qanday javob bermoqni bilmayman.",
}